return {
	"utilyre/barbecue.nvim",
	name = "barbecue",
	version = "*",
	event = { "BufReadPost", "BufNewFile", "BufWritePre" },
	dependencies = {
		"SmiteshP/nvim-navic",
		"nvim-tree/nvim-web-devicons",
	},
	opts = {
		kinds = {
			Array = "",
			Boolean = "",
			Class = "",
			Color = "",
			Constant = "ﲀ",
			Constructor = "",
			Enum = "",
			EnumMember = "",
			Event = "",
			Field = "ﰠ",
			File = "",
			Folder = "",
			Function = "ƒ",
			Interface = "蘒",
			Key = "",
			Keyword = "",
			Method = "",
			Module = "",
			Namespace = "",
			Null = "",
			Number = "ﳤ",
			Object = "פּ",
			Operator = "",
			Package = "",
			Property = "",
			Reference = "",
			Snippet = "",
			String = "",
			Struct = "פּ",
			Text = "",
			TypeParameter = "",
			Unit = "",
			Value = "",
			Variable = "",
		},
	},
}
